package com.changlu.agentforge.llm.chat.message;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Represents a message generated by the AI (language model).
 *
 * <p>Following LangChain4j's {@code AiMessage}, an AI message can carry:</p>
 * <ul>
 *   <li>{@link #text()} - textual content</li>
 *   <li>{@link #thinking()} - thinking/reasoning content</li>
 *   <li>{@link #toolExecutionRequests()} - requests to execute tools</li>
 *   <li>{@link #attributes()} - additional attributes, typically provider-specific</li>
 * </ul>
 *
 * <p>When this message contains tool execution requests, the application is expected to
 * execute them and append one {@link ToolExecutionResultMessage} per request to the
 * following conversation turn.</p>
 *
 * @author changlu
 * @since 2026-09-13
 */
public final class AiMessage implements ChatMessage {

    private final String text;
    private final String thinking;
    private final List<ToolExecutionRequest> toolExecutionRequests;
    private final Map<String, Object> attributes;

    public AiMessage(String text) {
        this(builder().text(text));
    }

    public AiMessage(List<ToolExecutionRequest> toolExecutionRequests) {
        this(builder().toolExecutionRequests(toolExecutionRequests));
    }

    public AiMessage(String text, List<ToolExecutionRequest> toolExecutionRequests) {
        this(builder().text(text).toolExecutionRequests(toolExecutionRequests));
    }

    private AiMessage(Builder builder) {
        this.text = builder.text;
        this.thinking = builder.thinking;
        this.toolExecutionRequests = immutableList(builder.toolExecutionRequests);
        this.attributes = immutableCopy(builder.attributes);
    }

    /**
     * Returns the textual content of this message, or {@code null} when the message
     * only carries {@link ToolExecutionRequest}s.
     *
     * @return message text, or {@code null}
     */
    @Override
    public String text() {
        return text;
    }

    /**
     * Returns the thinking/reasoning content, when present.
     *
     * @return thinking text, or {@code null}
     */
    public String thinking() {
        return thinking;
    }

    /**
     * Returns the tool execution requests carried by this message.
     *
     * @return possibly empty, immutable list of tool execution requests
     */
    public List<ToolExecutionRequest> toolExecutionRequests() {
        return toolExecutionRequests;
    }

    /**
     * Checks whether this message carries at least one {@link ToolExecutionRequest}.
     *
     * @return {@code true} when this message has tool execution requests
     */
    public boolean hasToolExecutionRequests() {
        return !toolExecutionRequests.isEmpty();
    }

    /**
     * Returns additional attributes, typically provider-specific.
     *
     * @return immutable map of attributes
     */
    public Map<String, Object> attributes() {
        return attributes;
    }

    @Override
    public ChatMessageType type() {
        return ChatMessageType.AI;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        AiMessage other = (AiMessage) obj;
        return Objects.equals(text, other.text)
                && Objects.equals(thinking, other.thinking)
                && Objects.equals(toolExecutionRequests, other.toolExecutionRequests)
                && Objects.equals(attributes, other.attributes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(text, thinking, toolExecutionRequests, attributes);
    }

    @Override
    public String toString() {
        return "AiMessage{"
                + "text='" + text + '\''
                + ", thinking='" + thinking + '\''
                + ", toolExecutionRequests=" + toolExecutionRequests
                + ", attributes=" + attributes
                + '}';
    }

    public Builder toBuilder() {
        return builder()
                .text(text)
                .thinking(thinking)
                .toolExecutionRequests(toolExecutionRequests)
                .attributes(attributes);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Creates a new text-only {@link AiMessage}.
     */
    public static AiMessage from(String text) {
        return new AiMessage(text);
    }

    /**
     * Creates a new {@link AiMessage} carrying only tool execution requests.
     */
    public static AiMessage from(ToolExecutionRequest... toolExecutionRequests) {
        if (toolExecutionRequests == null) {
            throw new NullPointerException("toolExecutionRequests");
        }
        List<ToolExecutionRequest> list = new ArrayList<ToolExecutionRequest>();
        Collections.addAll(list, toolExecutionRequests);
        return new AiMessage(list);
    }

    /**
     * Creates a new {@link AiMessage} carrying only tool execution requests.
     */
    public static AiMessage from(List<ToolExecutionRequest> toolExecutionRequests) {
        return new AiMessage(toolExecutionRequests);
    }

    /**
     * Creates a new {@link AiMessage} carrying both text and tool execution requests.
     */
    public static AiMessage from(String text, List<ToolExecutionRequest> toolExecutionRequests) {
        return new AiMessage(text, toolExecutionRequests);
    }

    public static AiMessage aiMessage(String text) {
        return from(text);
    }

    public static AiMessage aiMessage(ToolExecutionRequest... toolExecutionRequests) {
        return from(toolExecutionRequests);
    }

    public static AiMessage aiMessage(List<ToolExecutionRequest> toolExecutionRequests) {
        return from(toolExecutionRequests);
    }

    public static AiMessage aiMessage(String text, List<ToolExecutionRequest> toolExecutionRequests) {
        return from(text, toolExecutionRequests);
    }

    private static List<ToolExecutionRequest> immutableList(List<ToolExecutionRequest> values) {
        if (values == null || values.isEmpty()) {
            return Collections.emptyList();
        }
        return Collections.unmodifiableList(new ArrayList<ToolExecutionRequest>(values));
    }

    private static Map<String, Object> immutableCopy(Map<String, Object> source) {
        if (source == null || source.isEmpty()) {
            return Collections.emptyMap();
        }
        return Collections.unmodifiableMap(new LinkedHashMap<String, Object>(source));
    }

    public static final class Builder {

        private String text;
        private String thinking;
        private List<ToolExecutionRequest> toolExecutionRequests;
        private Map<String, Object> attributes;

        private Builder() {
        }

        public Builder text(String text) {
            this.text = text;
            return this;
        }

        public Builder thinking(String thinking) {
            this.thinking = thinking;
            return this;
        }

        public Builder toolExecutionRequests(List<ToolExecutionRequest> toolExecutionRequests) {
            this.toolExecutionRequests = toolExecutionRequests == null
                    ? Collections.<ToolExecutionRequest>emptyList()
                    : new ArrayList<ToolExecutionRequest>(toolExecutionRequests);
            return this;
        }

        public Builder attributes(Map<String, Object> attributes) {
            this.attributes = attributes == null
                    ? Collections.<String, Object>emptyMap()
                    : new LinkedHashMap<String, Object>(attributes);
            return this;
        }

        public AiMessage build() {
            return new AiMessage(this);
        }
    }
}