package com.changlu.agentforge.llm.chat.message;

import java.util.Objects;

/**
 * Represents a provider-neutral request generated by the model to execute a tool.
 *
 * <p>Both OpenAI {@code tool_calls.function} and Anthropic {@code tool_use} blocks
 * are normalized into this type before being carried by an {@link AiMessage}.</p>
 *
 * <p>Field semantics follow LangChain4j {@code ToolExecutionRequest}:</p>
 * <ul>
 *   <li>{@link #id()} - a unique identifier for the tool call, used to correlate the
 *       resulting {@link ToolExecutionResultMessage}.</li>
 *   <li>{@link #name()} - the name of the tool to execute.</li>
 *   <li>{@link #arguments()} - a raw JSON string holding the arguments of the call.</li>
 * </ul>
 *
 * @author changlu
 * @since 2026-09-13
 */
public final class ToolExecutionRequest {

    private final String id;
    private final String name;
    private final String arguments;

    private ToolExecutionRequest(Builder builder) {
        this.id = builder.id;
        this.name = builder.name;
        this.arguments = builder.arguments;
    }

    /**
     * Returns the identifier of this tool call.
     *
     * @return call id, or {@code null} when the provider did not supply one
     */
    public String id() {
        return id;
    }

    /**
     * Returns the name of the tool to execute.
     *
     * @return tool name
     */
    public String name() {
        return name;
    }

    /**
     * Returns the raw JSON arguments of the call.
     *
     * @return arguments JSON string, or {@code null}
     */
    public String arguments() {
        return arguments;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        ToolExecutionRequest other = (ToolExecutionRequest) obj;
        return Objects.equals(id, other.id)
                && Objects.equals(name, other.name)
                && Objects.equals(arguments, other.arguments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, arguments);
    }

    @Override
    public String toString() {
        return "ToolExecutionRequest{"
                + "id='" + id + '\''
                + ", name='" + name + '\''
                + ", arguments='" + arguments + '\''
                + '}';
    }

    public Builder toBuilder() {
        return builder()
                .id(id)
                .name(name)
                .arguments(arguments);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static ToolExecutionRequest from(String id, String name, String arguments) {
        return builder().id(id).name(name).arguments(arguments).build();
    }

    public static final class Builder {

        private String id;
        private String name;
        private String arguments;

        private Builder() {
        }

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder arguments(String arguments) {
            this.arguments = arguments;
            return this;
        }

        public ToolExecutionRequest build() {
            return new ToolExecutionRequest(this);
        }
    }
}